perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "it_IT.UTF-8",
	LC_ADDRESS = "it_IT.UTF-8",
	LC_MONETARY = "it_IT.UTF-8",
	LC_NUMERIC = "it_IT.UTF-8",
	LC_TELEPHONE = "it_IT.UTF-8",
	LC_IDENTIFICATION = "it_IT.UTF-8",
	LC_MEASUREMENT = "it_IT.UTF-8",
	LC_TIME = "it_IT.UTF-8",
	LC_NAME = "it_IT.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
2018-04-13 19:25:55,707 - SensorNodeFactory.create_nodes_auto() - INFO - skipping unknown node type
2018-04-13 19:25:55,709 - SensorNodeFactory.create_nodes_auto() - INFO - cc2538-bsl.py  -p /dev/ttyUSB1 -a 0x00202000
Opening port /dev/ttyUSB1, baud 500000 address 0x202000
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:11:F4:EB:44
2018-04-13 19:25:56,167 - SensorNodeFactory.create_nodes_auto() - INFO - b''
2018-04-13 19:25:56,168 - SensorNodeFactory.create_nodes_auto() - INFO - Found Zoul on /dev/ttyUSB1
2018-04-13 19:25:58,791 - CoAPWrapper.2.__init__() - INFO - sudo ../../agent_modules/contiki/communication_wrappers/bin/tunslip6 -C -B 115200 -s /dev/ttyUSB1 fd00:c:2::1/64
<wishful_module_gitar.lib_arm_cortex_m.Zoul object at 0x7372a750>
2018-04-13 19:25:59,888 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 inet `hostname` mtu 1500 up
2018-04-13 19:25:59,918 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fd00:c:2::1/64
2018-04-13 19:25:59,931 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fe80::c:2:0:1/64
2018-04-13 19:25:59,940 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0
2018-04-13 19:25:59,943 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-13 19:25:59,950 - Thread-1   - CoAPWrapper.2 - INFO - tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
2018-04-13 19:25:59,952 - Thread-1   - CoAPWrapper.2 - INFO - inet addr:127.0.0.1  P-t-P:127.0.0.1  Mask:255.255.255.255
2018-04-13 19:25:59,953 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fe80::c:2:0:1/64 Scope:Link
2018-04-13 19:25:59,955 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fd00:c:2::1/64 Scope:Global
2018-04-13 19:25:59,956 - Thread-1   - CoAPWrapper.2 - INFO - UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
2018-04-13 19:25:59,957 - Thread-1   - CoAPWrapper.2 - INFO - RX packets:0 errors:0 dropped:0 overruns:0 frame:0
2018-04-13 19:25:59,959 - Thread-1   - CoAPWrapper.2 - INFO - TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
2018-04-13 19:25:59,960 - Thread-1   - CoAPWrapper.2 - INFO - collisions:0 txqueuelen:500
2018-04-13 19:25:59,961 - Thread-1   - CoAPWrapper.2 - INFO - RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
2018-04-13 19:25:59,962 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-13 19:26:00,489 - Thread-1   - CoAPWrapper.2 - INFO - Got configuration message of type C
2018-04-13 19:26:00,491 - Thread-1   - CoAPWrapper.2 - INFO - Setting prefix fd00:c:2::
2018-04-13 19:26:00,492 - Thread-1   - CoAPWrapper.2 - INFO - Removing wishful_control_address: fd00:c::2
2018-04-13 19:26:00,494 - Thread-1   - CoAPWrapper.2 - INFO - New wishful_control_address: fd00:c:2::2
2018-04-13 19:26:01,476 - Thread-1   - CoAPWrapper.2 - INFO - Control prefix set and apps started
<Task pending coro=<coap_event_server() running at /export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py:106>>
2018-04-13 19:26:12,237 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-13 19:26:14,240 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-13 19:26:59,714 - Thread-1   - CoAPWrapper.2 - INFO - PEEE 15
2018-04-13 19:27:04,803 - Thread-1   - CoAPWrapper.2 - INFO - DEBUGG: RPL: Reset MRHOF
local monitor cp started - Name: ecoap_local_monitoring_program_rpl_cc, Id: 1 - STARTED
2018-04-13 19:27:18,749 - Thread-1   - CoAPWrapper.2 - INFO - DEBUGG: RPL: Reset MRHOF
2018-04-13 19:27:20,798 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-13 19:27:22,851 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-13 19:27:24,926 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-13 19:27:26,974 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-13 19:27:29,023 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-13 19:27:30,030 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-13 19:27:31,037 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-13 19:27:31,039 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-13 19:27:31,040 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-13 19:27:31,042 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-13 19:27:31,044 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-13 19:27:31,045 - local_control_program - Contiki Base Connector - INFO - Attr IEEE802154_measurement_macStats not found
2018-04-13 19:27:31,050 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-13 19:27:31,052 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-13 19:27:32,060 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-13 19:27:32,062 - local_control_program - Contiki Base Connector - INFO - Attr rpl_preferred_parent not found
2018-04-13 19:27:32,063 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-13 19:27:32,065 - local_control_program - Contiki Base Connector - INFO - Attr app_stats not found
2018-04-13 19:27:32,066 - local_control_program - Contiki Base Connector - INFO - Attr ipv6_stats not found
2018-04-13 19:27:32,067 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-13 19:27:32,068 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-13 19:27:32,070 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-13 19:27:32,071 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-13 19:27:32,072 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-13 19:27:32,074 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-13 19:27:49,322 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process startup initiated!
2018-04-13 19:27:49,324 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process started!
2018-04-13 19:28:13,746 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 8
2018-04-13 19:28:15,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 12
2018-04-13 19:28:16,245 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 13
2018-04-13 19:28:16,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 14
2018-04-13 19:28:24,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 30
2018-04-13 19:28:31,245 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 43
2018-04-13 19:28:31,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 44
2018-04-13 19:28:35,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 52
2018-04-13 19:28:36,245 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 53
2018-04-13 19:28:57,744 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 96
2018-04-13 19:28:58,244 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 97
2018-04-13 19:29:02,743 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 106
2018-04-13 19:29:14,244 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 129
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 274, in read_measurements
    resp_key_values[measurement.name] = measurement.datatype.read_bytes(response_message[line_ptr:])
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/lib_gitar.py", line 38, in read_bytes
    tpl = struct.unpack(tmp_fmt, buf)
struct.error: unpack requires a bytes object of length 2
2018-04-13 19:29:42,744 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 186
2018-04-13 19:29:43,283 - Thread-1   - CoAPWrapper.2 - INFO - OVERFLOW COAP: TRANS OVER
2018-04-13 19:29:43,329 - Dummy-225  - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:30:00,258 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 221
2018-04-13 19:30:01,956 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:30:02,460 - Dummy-31   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:30:11,258 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 243
2018-04-13 19:30:30,758 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 282
2018-04-13 19:30:40,257 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 301
2018-04-13 19:30:49,257 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 319
2018-04-13 19:31:10,756 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 362
2018-04-13 19:31:16,322 - Dummy-245  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
2018-04-13 19:31:16,326 - Dummy-225  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:31:17,256 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 375
2018-04-13 19:31:28,756 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 398
2018-04-13 19:31:35,028 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:31:35,507 - Dummy-31   - coap.requester - INFO - Request timed out
2018-04-13 19:31:41,256 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 423
2018-04-13 19:31:47,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 436
2018-04-13 19:31:52,756 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 446
2018-04-13 19:31:57,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 456
2018-04-13 19:32:01,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 464
2018-04-13 19:32:05,105 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:32:07,255 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 475
2018-04-13 19:32:10,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 482
2018-04-13 19:32:12,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 486
2018-04-13 19:32:13,255 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 487
2018-04-13 19:32:14,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 489
2018-04-13 19:32:14,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 490
2018-04-13 19:32:15,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 491
2018-04-13 19:32:15,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 492
2018-04-13 19:32:17,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 496
2018-04-13 19:32:18,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 497
2018-04-13 19:32:19,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 499
2018-04-13 19:32:19,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 500
2018-04-13 19:32:20,255 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 501
2018-04-13 19:32:20,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 502
2018-04-13 19:32:26,755 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 514
2018-04-13 19:32:28,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 518
2018-04-13 19:32:29,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 519
2018-04-13 19:32:31,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 523
2018-04-13 19:32:31,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 524
2018-04-13 19:32:36,254 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 533
2018-04-13 19:32:39,257 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 539
2018-04-13 19:32:49,754 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 560
2018-04-13 19:32:55,253 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 571
2018-04-13 19:33:21,753 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 624
2018-04-13 19:33:22,253 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 625
2018-04-13 19:33:22,757 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 626
2018-04-13 19:33:23,252 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 627
2018-04-13 19:33:23,756 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 628
2018-04-13 19:33:24,253 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 629
2018-04-13 19:33:24,753 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 630
2018-04-13 19:33:25,253 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 631
2018-04-13 19:33:34,252 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 649
2018-04-13 19:33:38,184 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:33:43,252 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 667
2018-04-13 19:34:02,252 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 705
2018-04-13 19:34:08,258 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:34:23,251 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 747
2018-04-13 19:34:48,750 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 798
2018-04-13 19:35:41,292 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:36:11,365 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:36:24,748 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 990
2018-04-13 19:36:27,248 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 995
2018-04-13 19:36:30,748 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1002
2018-04-13 19:37:04,747 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1070
2018-04-13 19:37:23,247 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1107
2018-04-13 19:37:44,441 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:37:47,745 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1156
2018-04-13 19:37:53,246 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1167
2018-04-13 19:38:14,515 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:38:20,245 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1221
2018-04-13 19:39:20,243 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1341
2018-04-13 19:39:26,743 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1354
2018-04-13 19:39:47,591 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:40:17,663 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:41:50,739 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-13 19:42:19,239 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1699
2018-04-13 19:42:20,818 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-13 19:43:53,845 - Dummy-26   - coap.requester - INFO - Request timed out
bash: line 1: 27211 Terminated              python agent.py --config ecoap_external_advanced/ecoap_agent.yaml
