perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "it_IT.UTF-8",
	LC_ADDRESS = "it_IT.UTF-8",
	LC_MONETARY = "it_IT.UTF-8",
	LC_NUMERIC = "it_IT.UTF-8",
	LC_TELEPHONE = "it_IT.UTF-8",
	LC_IDENTIFICATION = "it_IT.UTF-8",
	LC_MEASUREMENT = "it_IT.UTF-8",
	LC_TIME = "it_IT.UTF-8",
	LC_NAME = "it_IT.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
2018-04-14 11:07:23,319 - SensorNodeFactory.create_nodes_auto() - INFO - skipping unknown node type
2018-04-14 11:07:23,321 - SensorNodeFactory.create_nodes_auto() - INFO - cc2538-bsl.py  -p /dev/ttyUSB1 -a 0x00202000
Opening port /dev/ttyUSB1, baud 500000 address 0x202000
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:10:03:54:32
2018-04-14 11:07:23,773 - SensorNodeFactory.create_nodes_auto() - INFO - b''
2018-04-14 11:07:23,775 - SensorNodeFactory.create_nodes_auto() - INFO - Found Zoul on /dev/ttyUSB1
2018-04-14 11:07:26,372 - CoAPWrapper.2.__init__() - INFO - sudo ../../agent_modules/contiki/communication_wrappers/bin/tunslip6 -C -B 115200 -s /dev/ttyUSB1 fd00:c:2::1/64
<wishful_module_gitar.lib_arm_cortex_m.Zoul object at 0x73725770>
2018-04-14 11:07:27,478 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 inet `hostname` mtu 1500 up
2018-04-14 11:07:27,507 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fd00:c:2::1/64
2018-04-14 11:07:27,525 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fe80::c:2:0:1/64
2018-04-14 11:07:27,528 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0
2018-04-14 11:07:27,529 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-14 11:07:27,538 - Thread-1   - CoAPWrapper.2 - INFO - tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
2018-04-14 11:07:27,539 - Thread-1   - CoAPWrapper.2 - INFO - inet addr:127.0.0.1  P-t-P:127.0.0.1  Mask:255.255.255.255
2018-04-14 11:07:27,540 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fe80::c:2:0:1/64 Scope:Link
2018-04-14 11:07:27,541 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fd00:c:2::1/64 Scope:Global
2018-04-14 11:07:27,542 - Thread-1   - CoAPWrapper.2 - INFO - UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
2018-04-14 11:07:27,543 - Thread-1   - CoAPWrapper.2 - INFO - RX packets:0 errors:0 dropped:0 overruns:0 frame:0
2018-04-14 11:07:27,544 - Thread-1   - CoAPWrapper.2 - INFO - TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
2018-04-14 11:07:27,545 - Thread-1   - CoAPWrapper.2 - INFO - collisions:0 txqueuelen:500
2018-04-14 11:07:27,546 - Thread-1   - CoAPWrapper.2 - INFO - RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
2018-04-14 11:07:27,547 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-14 11:07:28,099 - Thread-1   - CoAPWrapper.2 - INFO - Got configuration message of type C
2018-04-14 11:07:28,100 - Thread-1   - CoAPWrapper.2 - INFO - Setting prefix fd00:c:2::
2018-04-14 11:07:28,100 - Thread-1   - CoAPWrapper.2 - INFO - Removing wishful_control_address: fd00:c::2
2018-04-14 11:07:28,101 - Thread-1   - CoAPWrapper.2 - INFO - New wishful_control_address: fd00:c:2::2
2018-04-14 11:07:29,086 - Thread-1   - CoAPWrapper.2 - INFO - Control prefix set and apps started
<Task pending coro=<coap_event_server() running at /export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py:106>>
2018-04-14 11:07:39,292 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-14 11:07:41,293 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-14 11:08:16,350 - Thread-1   - CoAPWrapper.2 - INFO - PEEE 5
2018-04-14 11:08:32,242 - Thread-1   - CoAPWrapper.2 - INFO - DEBUGG: RPL: Reset MRHOF
local monitor cp started - Name: ecoap_local_monitoring_program_rpl_cc, Id: 1 - STARTED
2018-04-14 11:08:46,577 - Thread-1   - CoAPWrapper.2 - INFO - DEBUGG: RPL: Reset MRHOF
2018-04-14 11:08:46,942 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-14 11:08:48,994 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-14 11:08:51,051 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-14 11:08:53,108 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-14 11:08:55,175 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-14 11:08:56,182 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-14 11:08:57,191 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-14 11:08:57,192 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-14 11:08:57,194 - local_control_program - Contiki Base Connector - INFO - Attr IEEE802154_measurement_macStats not found
2018-04-14 11:08:57,195 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-14 11:08:57,196 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-14 11:08:57,198 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-14 11:08:57,199 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-14 11:08:57,200 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-14 11:08:58,209 - local_control_program - Contiki Base Connector - INFO - Attr app_stats not found
2018-04-14 11:08:58,210 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-14 11:08:58,211 - local_control_program - Contiki Base Connector - INFO - Attr ipv6_stats not found
2018-04-14 11:08:58,212 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-14 11:08:58,213 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-14 11:08:58,214 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-14 11:08:58,215 - local_control_program - Contiki Base Connector - INFO - Attr rpl_preferred_parent not found
2018-04-14 11:08:58,216 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-14 11:08:58,216 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-14 11:08:58,217 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-14 11:08:58,218 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-14 11:09:04,315 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process startup initiated!
2018-04-14 11:09:04,317 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process started!
2018-04-14 11:09:48,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 29
2018-04-14 11:09:49,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 32
2018-04-14 11:09:50,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 33
2018-04-14 11:09:52,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 37
2018-04-14 11:09:52,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 38
2018-04-14 11:09:53,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 39
2018-04-14 11:09:53,944 - Thread-1   - CoAPWrapper.2 - INFO - OVERFLOW COAP: TRANS OVER
2018-04-14 11:09:53,983 - Dummy-60   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:09:57,487 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:09:58,360 - Dummy-31   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:10:03,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 59
2018-04-14 11:10:19,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 91
2018-04-14 11:10:50,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 153
2018-04-14 11:11:02,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 178
2018-04-14 11:11:05,912 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 184
2018-04-14 11:11:26,959 - Dummy-68   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:11:27,059 - Dummy-60   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:11:30,541 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:11:31,436 - Dummy-31   - coap.requester - INFO - Request timed out
2018-04-14 11:11:34,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 241
2018-04-14 11:12:00,607 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:12:07,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 307
2018-04-14 11:12:08,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 310
2018-04-14 11:12:09,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 311
2018-04-14 11:12:09,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 312
2018-04-14 11:12:23,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 339
2018-04-14 11:12:34,412 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 361
2018-04-14 11:12:42,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 378
2018-04-14 11:13:03,912 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 420
2018-04-14 11:13:11,912 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 436
2018-04-14 11:13:14,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 442
2018-04-14 11:13:21,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 455
2018-04-14 11:13:33,682 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:14:03,764 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:14:17,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 567
2018-04-14 11:14:44,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 622
2018-04-14 11:14:45,410 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 623
2018-04-14 11:14:45,910 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 624
2018-04-14 11:14:46,410 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 625
2018-04-14 11:14:46,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 626
2018-04-14 11:14:47,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 627
2018-04-14 11:14:47,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 628
2018-04-14 11:14:48,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 629
2018-04-14 11:15:29,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 711
2018-04-14 11:15:35,910 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 724
2018-04-14 11:15:36,839 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:15:36,910 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 726
2018-04-14 11:15:37,411 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 727
2018-04-14 11:15:37,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 728
2018-04-14 11:15:38,410 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 729
2018-04-14 11:15:40,910 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 734
2018-04-14 11:15:41,410 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 735
2018-04-14 11:15:42,911 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 738
2018-04-14 11:15:43,410 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 739
2018-04-14 11:15:43,910 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 740
2018-04-14 11:15:46,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 746
2018-04-14 11:15:55,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 764
2018-04-14 11:16:04,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 782
2018-04-14 11:16:05,919 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 784
2018-04-14 11:16:06,419 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 785
2018-04-14 11:16:06,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 786
2018-04-14 11:16:06,923 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:16:07,418 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 787
2018-04-14 11:16:27,418 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 827
2018-04-14 11:17:39,993 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:18:10,077 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:18:37,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1088
2018-04-14 11:18:42,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1098
2018-04-14 11:19:04,418 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1141
2018-04-14 11:19:17,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1168
2018-04-14 11:19:31,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1195
2018-04-14 11:19:43,141 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:20:06,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1266
2018-04-14 11:20:09,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1271
2018-04-14 11:20:09,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1272
2018-04-14 11:20:13,215 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:20:14,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1281
2018-04-14 11:20:15,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1283
2018-04-14 11:20:15,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1284
2018-04-14 11:20:16,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1285
2018-04-14 11:20:16,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1286
2018-04-14 11:20:18,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1290
2018-04-14 11:20:19,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1291
2018-04-14 11:20:19,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1292
2018-04-14 11:20:20,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1294
2018-04-14 11:20:21,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1295
2018-04-14 11:20:21,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1296
2018-04-14 11:20:22,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1297
2018-04-14 11:20:25,920 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1304
2018-04-14 11:20:55,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1364
2018-04-14 11:21:07,918 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1388
2018-04-14 11:21:18,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1409
2018-04-14 11:21:44,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1461
2018-04-14 11:21:46,234 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:21:46,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1466
2018-04-14 11:21:47,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1467
2018-04-14 11:21:48,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1470
2018-04-14 11:21:49,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1471
2018-04-14 11:21:49,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1472
2018-04-14 11:21:50,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1473
2018-04-14 11:21:50,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1474
2018-04-14 11:21:51,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1475
2018-04-14 11:21:51,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1476
2018-04-14 11:21:52,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1477
2018-04-14 11:21:52,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1478
2018-04-14 11:21:53,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1479
2018-04-14 11:21:53,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1480
2018-04-14 11:21:54,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1481
2018-04-14 11:21:54,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1482
2018-04-14 11:21:55,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1483
2018-04-14 11:21:55,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1484
2018-04-14 11:21:56,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1485
2018-04-14 11:21:56,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1486
2018-04-14 11:21:57,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1487
2018-04-14 11:21:57,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1488
2018-04-14 11:21:58,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1489
2018-04-14 11:21:58,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1490
2018-04-14 11:22:03,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1500
2018-04-14 11:22:16,316 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
2018-04-14 11:22:20,417 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1533
2018-04-14 11:22:45,917 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1584
2018-04-14 11:22:47,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1587
2018-04-14 11:22:47,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1588
2018-04-14 11:22:48,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1589
2018-04-14 11:22:48,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1590
2018-04-14 11:22:50,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1594
2018-04-14 11:22:51,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1595
2018-04-14 11:23:34,916 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1682
2018-04-14 11:23:35,416 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1683
2018-04-14 11:23:49,391 - Dummy-26   - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-14 11:24:19,469 - Dummy-26   - coap - INFO - Response not recognized - sending RST.
bash: line 1:  9835 Terminated              python agent.py --config ecoap_external_advanced/ecoap_agent.yaml
